logging.level.com.anahoret: INFO

app.config:
  profile-picture-api-router-pool-size: 10
  user-connection-api-router-pool-size: 10
  user-profile-api-router-pool-size: 10
  profile-picture-db-router-pool-size: 10
  user-connection-db-router-pool-size: 10
  user-profile-db-router-pool-size: 10
