logging.level.com.anahoret: INFO

app.config.profile-picture-api-router-pool-size: 10
app.config.user-connection-api-router-pool-size: 10
app.config.user-profile-api-router-pool-size: 10

app.config.profile-picture-db-router-pool-size: 10
app.config.user-connection-db-router-pool-size: 10
app.config.user-profile-db-router-pool-size: 10
