logging.level.com.anahoret: INFO

app.config:
  profile-picture-api-router-pool-size: 10
  user-connection-api-router-pool-size: 10
  user-profile-api-router-pool-size: 10
  profile-picture-db-router-pool-size: 10
  user-connection-db-router-pool-size: 10
  user-profile-db-router-pool-size: 10

db.config:
  driver-class: org.apache.derby.jdbc.EmbeddedDriver
  jdbc-url: jdbc:derby:memory:SCH_DB;create=true
  jdbc-username:
  jdbc-password:
  idle-connection-test-period-in-minutes: 60
  idle-max-age-in-minutes: 240
  max-connections-per-partition: 10
  min-connections-per-partition: 1
  partition-count: 2
  acquire-increment: 5
  statements-cache-size: 100

flyway:
  locations: db/migration
  baseline-version: 1
  sql-migration-prefix: migration_
  baseline-on-migrate: true
  schemas: APP

spring.jpa:
  hibernate:
    ddl-auto: validate
